name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file petclinic/pom.xml
    - name: run pipeline
      run: nohup java -jar petclinic/target/petclinic-2.2.2.BUILD-SNAPSHOT.jar &
    - name: Build test
      run: mvn --file petclinic-selenium/pom.xml -DskipTests install
    - name: run test
      run: mvn -Dtest=PetclinicTest --file petclinic-selenium/pom.xml -Dbrowser=firefox -Dheadless=false test

